# Generated by Django 4.2.4 on 2024-05-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('scoring_date', models.DateField()),
                ('province', models.CharField(max_length=100)),
            ],
        ),
    ]
